### ISSUE TITLE
NoClassDefFoundError for InteractiveShell

### ISSUE THREAD

**Issue by narendergupta** [IllinoisCogComp/illinois-sl-examples#1]
Here's the error while trying to run the ranking example from command line:

```
./scripts/run_reranking.sh trainRankingModel data/reranking/rerank.train config/StructuredPerceptron.config  rankModel

Exception in thread "main" java.lang.NoClassDefFoundError: edu/illinois/cs/cogcomp/core/utilities/commands/InteractiveShell
    at edu.illinois.cs.cogcomp.sl.applications.reranking.MainClass.main(MainClass.java:88)
Caused by: java.lang.ClassNotFoundException: edu.illinois.cs.cogcomp.core.utilities.commands.InteractiveShell
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 1 more

real    0m0.943s
user    0m0.084s
sys 0m0.016s

```

It might be because of some dependency issue.

**Comment by mssammon** [comment]
this is a illinois-core-utilities class...

**Comment by shyamupa** [comment]
Is this solved now?

**Comment by narendergupta** [comment]
Should I put an illinois-core dependency in this package's pom and commit? If yes, any specific version?

**Comment by narendergupta** [comment]
Yeah, it's resolved. It was my fault that I didn't run the mvn copy-dependency command before running reranker. It's working fine after that.
